alerting:
  alertmanagers:
  - static_configs:
    - targets: null
global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files: null
scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  static_configs:
  - targets:
    - localhost:9090
- job_name: "my_targets"
  file_sd_configs:
    - files:
        - /targets.json
