# Generated by Django 4.1.4 on 2023-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_number', models.IntegerField()),
                ('app_name', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=15)),
                ('date', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
    ]
