################################################################
################ Permit root login for workers ###############
################################################################

- name: PERMIT ROOT LOGIN
  hosts: workertemp
  become: yes
  vars:
    ansible_ssh_user: "student"
    ansible_sudo_pass: "capstone2022"

  tasks:

############### Copy sshd config ###############
  
  - name: copy sshd_config
    ansible.builtin.copy:
      src: /root/Ansible/files/sshd_config
      dest: /etc/ssh/sshd_config

############### restart sshd ###############

  - name: reset sshd
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: true
      name: sshd

################################################################
################ INSTALLATION SCRIPT FOR WORKERS ###############
################################################################

- name: INSTALLATION SCRIPT FOR WORKERS
  hosts: workertemp
  vars:
     ansible_ssh_user: "root"
  tasks:

############### Disable swap ###############

  - name: Disable swap
    shell: 'swapoff -a'

################ Install Docker ###############

  - name: Install docker
    ansible.builtin.apt:
      name: docker.io
      state: present

################ Install Transport ###############

  - name: Install Transport
    shell: 'apt-get install apt-transport-https curl -y'

################ Add repository ###############

  - name: Add keys
    shell: 'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add'

  - name: Add repository
    shell: ' apt-add-repository "deb https://apt.kubernetes.io/ kubernetes-xenial main" '

  - name: Update
    shell: ' apt update'

################ Install Kubernetes ###############

  - name: Install Kubeadm
    ansible.builtin.apt:
      name: kubeadm
      state: present

  - name: Install Kubelet
    ansible.builtin.apt:
      name: kubelet
      state: present

  - name: Install Kubectl
    ansible.builtin.apt:
      name: kubectl
      state: present

  - name: Install Kubernetes cni
    ansible.builtin.apt:
      name: kubernetes-cni
      state: present

################################################################
################ CREATE JOIN COMMAND ###############
################################################################

- name: CREATE JOIN COMMAND
  hosts: master
  tasks:

################ Get Token ###############

  - name: Get token
    shell: 'cp /etc/kubernetes/admin.conf $HOME/ && chown $(id -u):$(id -g) $HOME/admin.conf && export KUBECONFIG=$HOME/admin.conf && kubeadm token create --print-join-command'
    register: token
  
  - debug:
     var: token.stdout_lines

  - name: Save the token
    copy:
      content: "{{ token.stdout }}"
      dest: joincluster.sh
      mode: a+x
    delegate_to: localhost


################################################################
################ Join worker to cluster ########################
################################################################

- name: Join worker to cluster
  hosts: workertemp
  vars:
     ansible_ssh_user: "root"
  tasks:

################ Copy Join command ###############

  - name: Copy join to worker 
    copy:
      src: /root/joincluster.sh
      dest: /root/
      mode: a+x
      
################ Use join token ###############

  - name: Use join token
    shell: 'bash /root/joincluster.sh'
